### ISSUE TITLE
Show tab counter in popup and context menu

### ISSUE THREAD

**Issue by yfdyh000** [fonse/tab-workspaces#5]
It is necessary for tabs organization.

**Comment by fonse** [comment]
Yeah, I agree.

I'll try to add it soon!

**Comment by fonse** [comment]
@NicolasJEngler I added this counter in the branch `tab-counter`. Can you do the UI please?

**Comment by NicolasJEngler** [comment]
@fonse gotcha, already added a PR with the styles.

**Comment by fonse** [comment]
Shipped in https://github.com/fonse/tab-workspaces/pull/12
